finish startup script

diff --git a/bin/cms-java-ui b/bin/cms-java-ui
--- a/bin/cms-java-ui
+++ b/bin/cms-java-ui
@@ -4,9 +4,17 @@ if [ -z $DAQ_ROOT_DIR ]; then
     cd `dirname $0` && myDir=`pwd`
     setupFile=$myDir/../../setup.sh
     if [ ! -f $setupFile ]; then
-	echo "Cannot find setup file: $setupFile"
-		            exit 1
-			        fi
-				    source $setupFile
-				    fi
+        echo "Cannot find setup file: $setupFile"
+		exit 1
+    fi
+    source $setupFile
+fi
+
+uiJar=$CMS_ROOT_DIR/irmis/irmisBase/apps/deploy/irmisDeploy.jar
+if [ ! -f $uiJar ]; then
+    echo "Cannot file IRMIS jar file $uiJar."
+    exit 1
+fi
+java -jar $uiJar
+
 
